[project]
name = "aegiseval"
version = "0.1"
description = "this is a rag evaluation tool"
authors = [
    {name = "Your Name",email = "you@example.com"}
]
license = "n"
requires-python = "y"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
