"""add regression tables

Revision ID: 83040359de89
Revises: 246eacd77af7
Create Date: 2026-07-15 15:59:45.889332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83040359de89'
down_revision: Union[str, Sequence[str], None] = '246eacd77af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regression_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('baseline_run_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_run_id'], ['evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['candidate_run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_runs_baseline_run_id'), 'regression_runs', ['baseline_run_id'], unique=False)
    op.create_index(op.f('ix_regression_runs_candidate_run_id'), 'regression_runs', ['candidate_run_id'], unique=False)
    op.create_table('regression_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('regression_run_id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('candidate_value', sa.Float(), nullable=False),
    sa.Column('absolute_change', sa.Float(), nullable=False),
    sa.Column('relative_change', sa.Float(), nullable=True),
    sa.Column('threshold_type', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['regression_run_id'], ['regression_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_metrics_regression_run_id'), 'regression_metrics', ['regression_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regression_metrics_regression_run_id'), table_name='regression_metrics')
    op.drop_table('regression_metrics')
    op.drop_index(op.f('ix_regression_runs_candidate_run_id'), table_name='regression_runs')
    op.drop_index(op.f('ix_regression_runs_baseline_run_id'), table_name='regression_runs')
    op.drop_table('regression_runs')
    # ### end Alembic commands ###
